trigger:
  - master

pool: "default"

variables:
  keyVaultName: 'VaultUqacTP1'
  adminUsername: 'adminUser'

jobs:
  - job: BuildJob
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Compilation KeyVault'
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Abonnement Azure 1(3e4d952d-facf-4882-a757-e4f0d348b6fb)'
          subscriptionId: '3e4d952d-facf-4882-a757-e4f0d348b6fb'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'uqac-tp1-secrets-rg'
          location: 'East US'
          templateLocation: 'Linked artifact'
          csmFile: '$(Build.SourcesDirectory)/keyVault/azuredeploy.json'
          csmParametersFile: '$(Build.SourcesDirectory)/keyVault/azuredeploy.parameters.json'
          overrideParameters: '-vaults_VaultUqacTP1_name "$(keyVaultName)" -vmAdminUsername "$(adminUsername)" -vmAdminPassword "$(vmAdminPassword)"'
          deploymentMode: 'Validation'

      - task: PowerShell@2
        displayName: 'Test conversion Cloud-init.txt'
        inputs:
          targetType: 'inline'
          script: |
            $CloudContent = Get-Content -Path .\VMSS\Cloud-init.txt -Raw
            Write-Host $CloudContent
            $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
            Write-Host $encodedContent
            Write-Host "##vso[task.setvariable variable=CloudInitContent;]$encodedContent"

      - script: |
          echo $(CloudInitContent)

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Compilation wmsss'
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Abonnement Azure 1(3e4d952d-facf-4882-a757-e4f0d348b6fb)'
          subscriptionId: '3e4d952d-facf-4882-a757-e4f0d348b6fb'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'uqac-tp1-rg'
          location: 'Canada Central'
          templateLocation: 'Linked artifact'
          csmFile: '$(Build.SourcesDirectory)/VMSS/azuredeploy.json'
          csmParametersFile: '$(Build.SourcesDirectory)/VMSS/azuredeploy.parameters.json'
          overrideParameters: '-customData $(CloudInitContent) -adminPassword $(vmAdminPassword) -adminUsername $(adminUsername)'
          deploymentMode: 'Validation'
        condition: succeeded()

      - script: |
          echo "Compilation réussie, lancement du script de déploiement"